package com.sdv.kit.pexelsapp.presentation

import androidx.compose.ui.unit.dp

object Dimens {

    val PADDING_SMALL = 12.dp
    val PADDING_MEDIUM_SMALLER = 16.dp
    val PADDING_MEDIUM = 24.dp
    val PADDING_MEDIUM_BIGGER = 30.dp

    val SEARCH_BAR_SEARCH_ICON_SIZE = 16.dp
    val SEARCH_BAR_CLEAR_ICON_SIZE = 14.dp
    val SEARCH_BAR_MIN_HEIGHT = 50.dp

    val LOADING_PROGRESS_BAR_HEIGHT = 4.dp

    val FEATURED_COLLECTION_HEADER_HEIGHT = 39.dp

    val BOTTOM_NAVIGATION_HEIGHT = 64.dp
    val BOTTOM_NAVIGATION_ELEVATION = 15.dp
    val BOTTOM_NAVIGATION_ITEM_ICON_SIZE = 24.dp
    val BOTTOM_NAVIGATION_ITEM_INDICATOR_HEIGHT = 2.dp
    val BOTTOM_NAVIGATION_ITEM_INDICATOR_WIDTH = 22.dp

    const val PHOTO_CARD_HEIGHT_DELIMITER = 20
    const val PHOTO_AUTHOR_SECTION_ALPHA = 0.4f
    val PHOTO_AUTHOR_SECTION_MIN_HEIGHT = 33.dp

    val NO_NETWORK_STUB_HEIGHT = 147.dp
    val NO_NETWORK_STUB_WIDTH = 250.dp
    val BACK_BUTTON_SIZE = 40.dp

    val BACK_BUTTON_ICON_SIZE = 20.dp
    val DOWNLOAD_BUTTON_ICON_SIZE = 48.dp
    val DOWNLOAD_BUTTON_HEIGHT = 48.dp

    val DOWNLOAD_BUTTON_WIDTH = 180.dp

    val BOOKMARK_BUTTON_SIZE = 48.dp
}